export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};
import "../globals.css";

export default function AuthLayout({ children }: { children: React.ReactNode }) {
    return <div id="auth" className="h-full">{children}</div>;
}
